# Generated by Django 2.0.4 on 2018-05-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180506_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='nokiahealthmember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-05-10 22:11:31+00:00'),
        ),
        migrations.AddField(
            model_name='nokiahealthmember',
            name='last_updated',
            field=models.DateTimeField(default='2018-05-10 22:11:31+00:00'),
        ),
    ]
