# Generated by Django 2.0.4 on 2018-10-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180517_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='nokiahealthmember',
            name='access_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nokiahealthmember',
            name='expires_in',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nokiahealthmember',
            name='refresh_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nokiahealthmember',
            name='scope',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nokiahealthmember',
            name='token_type',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='nokiahealthmember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-10-03 15:34:37+00:00'),
        ),
        migrations.AlterField(
            model_name='nokiahealthmember',
            name='last_updated',
            field=models.DateTimeField(default='2018-10-03 15:34:37+00:00'),
        ),
    ]
